1 Server  =    ObjectCreateRule[className=org.apache.catalina.core.StandardServer, attributeName=className]
2 Server  =    SetPropertiesRule[]
3 Server  =    SetNextRule[methodName=setServer, paramType=org.apache.catalina.Server]
4 Server/GlobalNamingResources  =    ObjectCreateRule[className=org.apache.catalina.deploy.NamingResources, attributeName=null]
5 Server/GlobalNamingResources  =    SetPropertiesRule[]
6 Server/GlobalNamingResources  =    SetNextRule[methodName=setGlobalNamingResources, paramType=org.apache.catalina.deploy.NamingResources]
7 Server/Listener  =    ObjectCreateRule[className=null, attributeName=className]
8 Server/Listener  =    SetPropertiesRule[]
9 Server/Listener  =    SetNextRule[methodName=addLifecycleListener, paramType=org.apache.catalina.LifecycleListener]
10 Server/Service  =    ObjectCreateRule[className=org.apache.catalina.core.StandardService, attributeName=className]
11 Server/Service  =    SetPropertiesRule[]
12 Server/Service  =    SetNextRule[methodName=addService, paramType=org.apache.catalina.Service]
13 Server/Service/Listener  =    ObjectCreateRule[className=null, attributeName=className]
14 Server/Service/Listener  =    SetPropertiesRule[]
15 Server/Service/Listener  =    SetNextRule[methodName=addLifecycleListener, paramType=org.apache.catalina.LifecycleListener]
16 Server/Service/Executor  =    ObjectCreateRule[className=org.apache.catalina.core.StandardThreadExecutor, attributeName=className]
17 Server/Service/Executor  =    SetPropertiesRule[]
18 Server/Service/Executor  =    SetNextRule[methodName=addExecutor, paramType=org.apache.catalina.Executor]
19 Server/Service/Connector  =    org.apache.catalina.startup.ConnectorCreateRule@1e4cbc4
20 Server/Service/Connector  =    org.apache.catalina.startup.SetAllPropertiesRule@1fdc96c
21 Server/Service/Connector  =    SetNextRule[methodName=addConnector, paramType=org.apache.catalina.connector.Connector]
22 Server/Service/Connector/Listener  =    ObjectCreateRule[className=null, attributeName=className]
23 Server/Service/Connector/Listener  =    SetPropertiesRule[]
24 Server/Service/Connector/Listener  =    SetNextRule[methodName=addLifecycleListener, paramType=org.apache.catalina.LifecycleListener]
25 Server/GlobalNamingResources/Ejb  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextEjb, attributeName=null]
26 Server/GlobalNamingResources/Ejb  =    org.apache.catalina.startup.SetAllPropertiesRule@b2fd8f
27 Server/GlobalNamingResources/Ejb  =    SetNextRule[methodName=addEjb, paramType=org.apache.catalina.deploy.ContextEjb]
28 Server/GlobalNamingResources/Environment  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextEnvironment, attributeName=null]
29 Server/GlobalNamingResources/Environment  =    SetPropertiesRule[]
30 Server/GlobalNamingResources/Environment  =    SetNextRule[methodName=addEnvironment, paramType=org.apache.catalina.deploy.ContextEnvironment]
31 Server/GlobalNamingResources/LocalEjb  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextLocalEjb, attributeName=null]
32 Server/GlobalNamingResources/LocalEjb  =    org.apache.catalina.startup.SetAllPropertiesRule@124bbbf
33 Server/GlobalNamingResources/LocalEjb  =    SetNextRule[methodName=addLocalEjb, paramType=org.apache.catalina.deploy.ContextLocalEjb]
34 Server/GlobalNamingResources/Resource  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextResource, attributeName=null]
35 Server/GlobalNamingResources/Resource  =    org.apache.catalina.startup.SetAllPropertiesRule@a20892
36 Server/GlobalNamingResources/Resource  =    SetNextRule[methodName=addResource, paramType=org.apache.catalina.deploy.ContextResource]
37 Server/GlobalNamingResources/ResourceEnvRef  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextResourceEnvRef, attributeName=null]
38 Server/GlobalNamingResources/ResourceEnvRef  =    org.apache.catalina.startup.SetAllPropertiesRule@1e0bc08
39 Server/GlobalNamingResources/ResourceEnvRef  =    SetNextRule[methodName=addResourceEnvRef, paramType=org.apache.catalina.deploy.ContextResourceEnvRef]
40 Server/GlobalNamingResources/ServiceRef  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextService, attributeName=null]
41 Server/GlobalNamingResources/ServiceRef  =    org.apache.catalina.startup.SetAllPropertiesRule@158b649
42 Server/GlobalNamingResources/ServiceRef  =    SetNextRule[methodName=addService, paramType=org.apache.catalina.deploy.ContextService]
43 Server/GlobalNamingResources/Transaction  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextTransaction, attributeName=null]
44 Server/GlobalNamingResources/Transaction  =    org.apache.catalina.startup.SetAllPropertiesRule@127734f
45 Server/GlobalNamingResources/Transaction  =    SetNextRule[methodName=setTransaction, paramType=org.apache.catalina.deploy.ContextTransaction]
46 Server/Service/Engine  =    ObjectCreateRule[className=org.apache.catalina.core.StandardEngine, attributeName=className]
47 Server/Service/Engine  =    SetPropertiesRule[]
48 Server/Service/Engine  =    org.apache.catalina.startup.LifecycleListenerRule@1037c71
49 Server/Service/Engine  =    SetNextRule[methodName=setContainer, paramType=org.apache.catalina.Container]
50 Server/Service/Engine/Cluster  =    ObjectCreateRule[className=null, attributeName=className]
51 Server/Service/Engine/Cluster  =    SetPropertiesRule[]
52 Server/Service/Engine/Cluster  =    SetNextRule[methodName=setCluster, paramType=org.apache.catalina.Cluster]
53 Server/Service/Engine/Listener  =    ObjectCreateRule[className=null, attributeName=className]
54 Server/Service/Engine/Listener  =    SetPropertiesRule[]
55 Server/Service/Engine/Listener  =    SetNextRule[methodName=addLifecycleListener, paramType=org.apache.catalina.LifecycleListener]
56 Server/Service/Engine/Realm  =    ObjectCreateRule[className=null, attributeName=className]
57 Server/Service/Engine/Realm  =    SetPropertiesRule[]
58 Server/Service/Engine/Realm  =    SetNextRule[methodName=setRealm, paramType=org.apache.catalina.Realm]
59 Server/Service/Engine/Realm/Realm  =    ObjectCreateRule[className=null, attributeName=className]
60 Server/Service/Engine/Realm/Realm  =    SetPropertiesRule[]
61 Server/Service/Engine/Realm/Realm  =    SetNextRule[methodName=addRealm, paramType=org.apache.catalina.Realm]
62 Server/Service/Engine/Valve  =    ObjectCreateRule[className=null, attributeName=className]
63 Server/Service/Engine/Valve  =    SetPropertiesRule[]
64 Server/Service/Engine/Valve  =    SetNextRule[methodName=addValve, paramType=org.apache.catalina.Valve]
65 Server/Service/Engine/Host  =    ObjectCreateRule[className=org.apache.catalina.core.StandardHost, attributeName=className]
66 Server/Service/Engine/Host  =    SetPropertiesRule[]
67 Server/Service/Engine/Host  =    org.apache.catalina.startup.CopyParentClassLoaderRule@1df073d
68 Server/Service/Engine/Host  =    org.apache.catalina.startup.LifecycleListenerRule@1546e25
69 Server/Service/Engine/Host  =    SetNextRule[methodName=addChild, paramType=org.apache.catalina.Container]
70 Server/Service/Engine/Host/Alias  =    CallMethodRule[methodName=addAlias, paramCount=0, paramTypes={java.lang.String}]
71 Server/Service/Engine/Host/Cluster  =    ObjectCreateRule[className=null, attributeName=className]
72 Server/Service/Engine/Host/Cluster  =    SetPropertiesRule[]
73 Server/Service/Engine/Host/Cluster  =    SetNextRule[methodName=setCluster, paramType=org.apache.catalina.Cluster]
74 Server/Service/Engine/Host/Listener  =    ObjectCreateRule[className=null, attributeName=className]
75 Server/Service/Engine/Host/Listener  =    SetPropertiesRule[]
76 Server/Service/Engine/Host/Listener  =    SetNextRule[methodName=addLifecycleListener, paramType=org.apache.catalina.LifecycleListener]
77 Server/Service/Engine/Host/Realm  =    ObjectCreateRule[className=null, attributeName=className]
78 Server/Service/Engine/Host/Realm  =    SetPropertiesRule[]
79 Server/Service/Engine/Host/Realm  =    SetNextRule[methodName=setRealm, paramType=org.apache.catalina.Realm]
80 Server/Service/Engine/Host/Realm/Realm  =    ObjectCreateRule[className=null, attributeName=className]
81 Server/Service/Engine/Host/Realm/Realm  =    SetPropertiesRule[]
82 Server/Service/Engine/Host/Realm/Realm  =    SetNextRule[methodName=addRealm, paramType=org.apache.catalina.Realm]
83 Server/Service/Engine/Host/Valve  =    ObjectCreateRule[className=null, attributeName=className]
84 Server/Service/Engine/Host/Valve  =    SetPropertiesRule[]
85 Server/Service/Engine/Host/Valve  =    SetNextRule[methodName=addValve, paramType=org.apache.catalina.Valve]
86 Server/Service/Engine/Host/Context  =    ObjectCreateRule[className=org.apache.catalina.core.StandardContext, attributeName=className]
87 Server/Service/Engine/Host/Context  =    SetPropertiesRule[]
88 Server/Service/Engine/Host/Context  =    org.apache.catalina.startup.LifecycleListenerRule@b66cc
89 Server/Service/Engine/Host/Context  =    SetNextRule[methodName=addChild, paramType=org.apache.catalina.Container]
90 Server/Service/Engine/Host/Context/InstanceListener  =    CallMethodRule[methodName=addInstanceListener, paramCount=0, paramTypes={java.lang.String}]
91 Server/Service/Engine/Host/Context/Listener  =    ObjectCreateRule[className=null, attributeName=className]
92 Server/Service/Engine/Host/Context/Listener  =    SetPropertiesRule[]
93 Server/Service/Engine/Host/Context/Listener  =    SetNextRule[methodName=addLifecycleListener, paramType=org.apache.catalina.LifecycleListener]
94 Server/Service/Engine/Host/Context/Loader  =    ObjectCreateRule[className=org.apache.catalina.loader.WebappLoader, attributeName=className]
95 Server/Service/Engine/Host/Context/Loader  =    SetPropertiesRule[]
96 Server/Service/Engine/Host/Context/Loader  =    SetNextRule[methodName=setLoader, paramType=org.apache.catalina.Loader]
97 Server/Service/Engine/Host/Context/Manager  =    ObjectCreateRule[className=org.apache.catalina.session.StandardManager, attributeName=className]
98 Server/Service/Engine/Host/Context/Manager  =    SetPropertiesRule[]
99 Server/Service/Engine/Host/Context/Manager  =    SetNextRule[methodName=setManager, paramType=org.apache.catalina.Manager]
100 Server/Service/Engine/Host/Context/Manager/Store  =    ObjectCreateRule[className=null, attributeName=className]
101 Server/Service/Engine/Host/Context/Manager/Store  =    SetPropertiesRule[]
102 Server/Service/Engine/Host/Context/Manager/Store  =    SetNextRule[methodName=setStore, paramType=org.apache.catalina.Store]
103 Server/Service/Engine/Host/Context/Parameter  =    ObjectCreateRule[className=org.apache.catalina.deploy.ApplicationParameter, attributeName=null]
104 Server/Service/Engine/Host/Context/Parameter  =    SetPropertiesRule[]
105 Server/Service/Engine/Host/Context/Parameter  =    SetNextRule[methodName=addApplicationParameter, paramType=org.apache.catalina.deploy.ApplicationParameter]
106 Server/Service/Engine/Host/Context/Realm  =    ObjectCreateRule[className=null, attributeName=className]
107 Server/Service/Engine/Host/Context/Realm  =    SetPropertiesRule[]
108 Server/Service/Engine/Host/Context/Realm  =    SetNextRule[methodName=setRealm, paramType=org.apache.catalina.Realm]
109 Server/Service/Engine/Host/Context/Realm/Realm  =    ObjectCreateRule[className=null, attributeName=className]
110 Server/Service/Engine/Host/Context/Realm/Realm  =    SetPropertiesRule[]
111 Server/Service/Engine/Host/Context/Realm/Realm  =    SetNextRule[methodName=addRealm, paramType=org.apache.catalina.Realm]
112 Server/Service/Engine/Host/Context/Resources  =    ObjectCreateRule[className=org.apache.naming.resources.FileDirContext, attributeName=className]
113 Server/Service/Engine/Host/Context/Resources  =    SetPropertiesRule[]
114 Server/Service/Engine/Host/Context/Resources  =    SetNextRule[methodName=setResources, paramType=javax.naming.directory.DirContext]
115 Server/Service/Engine/Host/Context/ResourceLink  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextResourceLink, attributeName=null]
116 Server/Service/Engine/Host/Context/ResourceLink  =    SetPropertiesRule[]
117 Server/Service/Engine/Host/Context/ResourceLink  =    SetNextRule[methodName=addResourceLink, paramType=org.apache.catalina.deploy.ContextResourceLink]
118 Server/Service/Engine/Host/Context/Valve  =    ObjectCreateRule[className=null, attributeName=className]
119 Server/Service/Engine/Host/Context/Valve  =    SetPropertiesRule[]
120 Server/Service/Engine/Host/Context/Valve  =    SetNextRule[methodName=addValve, paramType=org.apache.catalina.Valve]
121 Server/Service/Engine/Host/Context/WatchedResource  =    CallMethodRule[methodName=addWatchedResource, paramCount=0, paramTypes={java.lang.String}]
122 Server/Service/Engine/Host/Context/WrapperLifecycle  =    CallMethodRule[methodName=addWrapperLifecycle, paramCount=0, paramTypes={java.lang.String}]
123 Server/Service/Engine/Host/Context/WrapperListener  =    CallMethodRule[methodName=addWrapperListener, paramCount=0, paramTypes={java.lang.String}]
124 Server/Service/Engine/Host/Context/JarScanner  =    ObjectCreateRule[className=org.apache.tomcat.util.scan.StandardJarScanner, attributeName=className]
125 Server/Service/Engine/Host/Context/JarScanner  =    SetPropertiesRule[]
126 Server/Service/Engine/Host/Context/JarScanner  =    SetNextRule[methodName=setJarScanner, paramType=org.apache.tomcat.JarScanner]
127 Server/Service/Engine/Host/Cluster/Manager  =    ObjectCreateRule[className=null, attributeName=className]
128 Server/Service/Engine/Host/Cluster/Manager  =    SetPropertiesRule[]
129 Server/Service/Engine/Host/Cluster/Manager  =    SetNextRule[methodName=setManagerTemplate, paramType=org.apache.catalina.ha.ClusterManager]
130 Server/Service/Engine/Host/Cluster/Channel  =    ObjectCreateRule[className=null, attributeName=className]
131 Server/Service/Engine/Host/Cluster/Channel  =    SetPropertiesRule[]
132 Server/Service/Engine/Host/Cluster/Channel  =    SetNextRule[methodName=setChannel, paramType=org.apache.catalina.tribes.Channel]
133 Server/Service/Engine/Host/Cluster/Channel/Membership  =    ObjectCreateRule[className=null, attributeName=className]
134 Server/Service/Engine/Host/Cluster/Channel/Membership  =    SetPropertiesRule[]
135 Server/Service/Engine/Host/Cluster/Channel/Membership  =    SetNextRule[methodName=setMembershipService, paramType=org.apache.catalina.tribes.MembershipService]
136 Server/Service/Engine/Host/Cluster/Channel/Sender  =    ObjectCreateRule[className=null, attributeName=className]
137 Server/Service/Engine/Host/Cluster/Channel/Sender  =    SetPropertiesRule[]
138 Server/Service/Engine/Host/Cluster/Channel/Sender  =    SetNextRule[methodName=setChannelSender, paramType=org.apache.catalina.tribes.ChannelSender]
139 Server/Service/Engine/Host/Cluster/Channel/Sender/Transport  =    ObjectCreateRule[className=null, attributeName=className]
140 Server/Service/Engine/Host/Cluster/Channel/Sender/Transport  =    SetPropertiesRule[]
141 Server/Service/Engine/Host/Cluster/Channel/Sender/Transport  =    SetNextRule[methodName=setTransport, paramType=org.apache.catalina.tribes.transport.MultiPointSender]
142 Server/Service/Engine/Host/Cluster/Channel/Receiver  =    ObjectCreateRule[className=null, attributeName=className]
143 Server/Service/Engine/Host/Cluster/Channel/Receiver  =    SetPropertiesRule[]
144 Server/Service/Engine/Host/Cluster/Channel/Receiver  =    SetNextRule[methodName=setChannelReceiver, paramType=org.apache.catalina.tribes.ChannelReceiver]
145 Server/Service/Engine/Host/Cluster/Channel/Interceptor  =    ObjectCreateRule[className=null, attributeName=className]
146 Server/Service/Engine/Host/Cluster/Channel/Interceptor  =    SetPropertiesRule[]
147 Server/Service/Engine/Host/Cluster/Channel/Interceptor  =    SetNextRule[methodName=addInterceptor, paramType=org.apache.catalina.tribes.ChannelInterceptor]
148 Server/Service/Engine/Host/Cluster/Channel/Interceptor/Member  =    ObjectCreateRule[className=null, attributeName=className]
149 Server/Service/Engine/Host/Cluster/Channel/Interceptor/Member  =    SetPropertiesRule[]
150 Server/Service/Engine/Host/Cluster/Channel/Interceptor/Member  =    SetNextRule[methodName=addStaticMember, paramType=org.apache.catalina.tribes.Member]
151 Server/Service/Engine/Host/Cluster/Valve  =    ObjectCreateRule[className=null, attributeName=className]
152 Server/Service/Engine/Host/Cluster/Valve  =    SetPropertiesRule[]
153 Server/Service/Engine/Host/Cluster/Valve  =    SetNextRule[methodName=addValve, paramType=org.apache.catalina.Valve]
154 Server/Service/Engine/Host/Cluster/Deployer  =    ObjectCreateRule[className=null, attributeName=className]
155 Server/Service/Engine/Host/Cluster/Deployer  =    SetPropertiesRule[]
156 Server/Service/Engine/Host/Cluster/Deployer  =    SetNextRule[methodName=setClusterDeployer, paramType=org.apache.catalina.ha.ClusterDeployer]
157 Server/Service/Engine/Host/Cluster/Listener  =    ObjectCreateRule[className=null, attributeName=className]
158 Server/Service/Engine/Host/Cluster/Listener  =    SetPropertiesRule[]
159 Server/Service/Engine/Host/Cluster/Listener  =    SetNextRule[methodName=addLifecycleListener, paramType=org.apache.catalina.LifecycleListener]
160 Server/Service/Engine/Host/Cluster/ClusterListener  =    ObjectCreateRule[className=null, attributeName=className]
161 Server/Service/Engine/Host/Cluster/ClusterListener  =    SetPropertiesRule[]
162 Server/Service/Engine/Host/Cluster/ClusterListener  =    SetNextRule[methodName=addClusterListener, paramType=org.apache.catalina.ha.ClusterListener]
163 Server/Service/Engine/Host/Context/Ejb  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextEjb, attributeName=null]
164 Server/Service/Engine/Host/Context/Ejb  =    org.apache.catalina.startup.SetAllPropertiesRule@8a0d5d
165 Server/Service/Engine/Host/Context/Ejb  =    SetNextRule[methodName=addEjb, paramType=org.apache.catalina.deploy.ContextEjb]
166 Server/Service/Engine/Host/Context/Environment  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextEnvironment, attributeName=null]
167 Server/Service/Engine/Host/Context/Environment  =    SetPropertiesRule[]
168 Server/Service/Engine/Host/Context/Environment  =    SetNextRule[methodName=addEnvironment, paramType=org.apache.catalina.deploy.ContextEnvironment]
169 Server/Service/Engine/Host/Context/LocalEjb  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextLocalEjb, attributeName=null]
170 Server/Service/Engine/Host/Context/LocalEjb  =    org.apache.catalina.startup.SetAllPropertiesRule@173831b
171 Server/Service/Engine/Host/Context/LocalEjb  =    SetNextRule[methodName=addLocalEjb, paramType=org.apache.catalina.deploy.ContextLocalEjb]
172 Server/Service/Engine/Host/Context/Resource  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextResource, attributeName=null]
173 Server/Service/Engine/Host/Context/Resource  =    org.apache.catalina.startup.SetAllPropertiesRule@a470b8
174 Server/Service/Engine/Host/Context/Resource  =    SetNextRule[methodName=addResource, paramType=org.apache.catalina.deploy.ContextResource]
175 Server/Service/Engine/Host/Context/ResourceEnvRef  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextResourceEnvRef, attributeName=null]
176 Server/Service/Engine/Host/Context/ResourceEnvRef  =    org.apache.catalina.startup.SetAllPropertiesRule@1e4457d
177 Server/Service/Engine/Host/Context/ResourceEnvRef  =    SetNextRule[methodName=addResourceEnvRef, paramType=org.apache.catalina.deploy.ContextResourceEnvRef]
178 Server/Service/Engine/Host/Context/ServiceRef  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextService, attributeName=null]
179 Server/Service/Engine/Host/Context/ServiceRef  =    org.apache.catalina.startup.SetAllPropertiesRule@18e2b22
180 Server/Service/Engine/Host/Context/ServiceRef  =    SetNextRule[methodName=addService, paramType=org.apache.catalina.deploy.ContextService]
181 Server/Service/Engine/Host/Context/Transaction  =    ObjectCreateRule[className=org.apache.catalina.deploy.ContextTransaction, attributeName=null]
182 Server/Service/Engine/Host/Context/Transaction  =    org.apache.catalina.startup.SetAllPropertiesRule@b1c5fa
183 Server/Service/Engine/Host/Context/Transaction  =    SetNextRule[methodName=setTransaction, paramType=org.apache.catalina.deploy.ContextTransaction]
184 Server/Service/Engine  =    org.apache.catalina.startup.SetParentClassLoaderRule@13caecd
185 Server/Service/Engine/Cluster/Manager  =    ObjectCreateRule[className=null, attributeName=className]
186 Server/Service/Engine/Cluster/Manager  =    SetPropertiesRule[]
187 Server/Service/Engine/Cluster/Manager  =    SetNextRule[methodName=setManagerTemplate, paramType=org.apache.catalina.ha.ClusterManager]
188 Server/Service/Engine/Cluster/Channel  =    ObjectCreateRule[className=null, attributeName=className]
189 Server/Service/Engine/Cluster/Channel  =    SetPropertiesRule[]
190 Server/Service/Engine/Cluster/Channel  =    SetNextRule[methodName=setChannel, paramType=org.apache.catalina.tribes.Channel]
191 Server/Service/Engine/Cluster/Channel/Membership  =    ObjectCreateRule[className=null, attributeName=className]
192 Server/Service/Engine/Cluster/Channel/Membership  =    SetPropertiesRule[]
193 Server/Service/Engine/Cluster/Channel/Membership  =    SetNextRule[methodName=setMembershipService, paramType=org.apache.catalina.tribes.MembershipService]
194 Server/Service/Engine/Cluster/Channel/Sender  =    ObjectCreateRule[className=null, attributeName=className]
195 Server/Service/Engine/Cluster/Channel/Sender  =    SetPropertiesRule[]
196 Server/Service/Engine/Cluster/Channel/Sender  =    SetNextRule[methodName=setChannelSender, paramType=org.apache.catalina.tribes.ChannelSender]
197 Server/Service/Engine/Cluster/Channel/Sender/Transport  =    ObjectCreateRule[className=null, attributeName=className]
198 Server/Service/Engine/Cluster/Channel/Sender/Transport  =    SetPropertiesRule[]
199 Server/Service/Engine/Cluster/Channel/Sender/Transport  =    SetNextRule[methodName=setTransport, paramType=org.apache.catalina.tribes.transport.MultiPointSender]
200 Server/Service/Engine/Cluster/Channel/Receiver  =    ObjectCreateRule[className=null, attributeName=className]
201 Server/Service/Engine/Cluster/Channel/Receiver  =    SetPropertiesRule[]
202 Server/Service/Engine/Cluster/Channel/Receiver  =    SetNextRule[methodName=setChannelReceiver, paramType=org.apache.catalina.tribes.ChannelReceiver]
203 Server/Service/Engine/Cluster/Channel/Interceptor  =    ObjectCreateRule[className=null, attributeName=className]
204 Server/Service/Engine/Cluster/Channel/Interceptor  =    SetPropertiesRule[]
205 Server/Service/Engine/Cluster/Channel/Interceptor  =    SetNextRule[methodName=addInterceptor, paramType=org.apache.catalina.tribes.ChannelInterceptor]
206 Server/Service/Engine/Cluster/Channel/Interceptor/Member  =    ObjectCreateRule[className=null, attributeName=className]
207 Server/Service/Engine/Cluster/Channel/Interceptor/Member  =    SetPropertiesRule[]
208 Server/Service/Engine/Cluster/Channel/Interceptor/Member  =    SetNextRule[methodName=addStaticMember, paramType=org.apache.catalina.tribes.Member]
209 Server/Service/Engine/Cluster/Valve  =    ObjectCreateRule[className=null, attributeName=className]
210 Server/Service/Engine/Cluster/Valve  =    SetPropertiesRule[]
211 Server/Service/Engine/Cluster/Valve  =    SetNextRule[methodName=addValve, paramType=org.apache.catalina.Valve]
212 Server/Service/Engine/Cluster/Deployer  =    ObjectCreateRule[className=null, attributeName=className]
213 Server/Service/Engine/Cluster/Deployer  =    SetPropertiesRule[]
214 Server/Service/Engine/Cluster/Deployer  =    SetNextRule[methodName=setClusterDeployer, paramType=org.apache.catalina.ha.ClusterDeployer]
215 Server/Service/Engine/Cluster/Listener  =    ObjectCreateRule[className=null, attributeName=className]
216 Server/Service/Engine/Cluster/Listener  =    SetPropertiesRule[]
217 Server/Service/Engine/Cluster/Listener  =    SetNextRule[methodName=addLifecycleListener, paramType=org.apache.catalina.LifecycleListener]
218 Server/Service/Engine/Cluster/ClusterListener  =    ObjectCreateRule[className=null, attributeName=className]
219 Server/Service/Engine/Cluster/ClusterListener  =    SetPropertiesRule[]
220 Server/Service/Engine/Cluster/ClusterListener  =    SetNextRule[methodName=addClusterListener, paramType=org.apache.catalina.ha.ClusterListener]
